### ISSUE TITLE
Show enrolled students to instructors

### ISSUE THREAD

**Issue by simonldwg** [U2Vj/turtl#67]
Show all enrolled students to the instructors of a classroom at `http://<frontend>/instructor/classrooms/<classroom_id>`

Possible endpoint: `GET /enrollments/for-classroom/<classroom_id>`. Permission check: Only instructors of the specified classroom can access this endpoint.

**Comment by Dario638** [comment]
Added endpoint to backend.

**Comment by LcAbrgr** [comment]
Add Enrolled Students Table
