### ISSUE TITLE
Fix shell in backend

### ISSUE THREAD

**Issue by simonldwg** [U2Vj/turtl#72]
* Fix error `AttributeError: 'function' object has no attribute 'get'`

![grafik](https://github.com/U2Vj/turtl/assets/12676587/ff186784-a628-4e4c-abd7-f72d18ce7e97)

**Comment by Dario638** [comment]
Shell is working as of 2e16eef1f05bfa299fc34a8c0d30d89b233630a1

There are still some issues though:
* Container is still hardcoded
* Commands are echoed back to the shell
  * AttachAddon was replaced with manual WebSocket communication but this did not fix the issue
* Command buffer is client sided, so interactive commands are not handled well
* Some interactive applications like vim don't work at all
* No support for signals like SIGINT
